# Use 'bundle exec jekyll build' to create files for github
# Use 'bundle exec jekyll serve --config _config.yml, _config_dev.yml'
title: micromatt.tech
email: matt@micromatt.tech
description: The Blog & Portfolio of Matthew Law.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://micromatt.tech" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:categories/:year-:month-:day/:title/
twitter:
  username: chuffs97
logo: /assests/circlelogo.png
github_username:  Chuffs
future: true

# Google Tag Manager
google:
  tag_manager:
    container_id: GTM-WQS8N26

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

show_drafts: false

# collections
collections:
  comments:
    output: false
  projects:
    output: true

#custom variables
youtube: "https://www.youtube.com/channel/UCsjYwlaeT48XV7kxRLkE6bw"
github: "https://github.com/Chuffs"
twitter: "https://twitter.com/chuffs97"

name: micromatt.tech

micromatt-green: 6ac68f
micromatt-blue: 649cb4

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
